version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1234
      - N8N_HOST=n8n.yourdomain.com
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=https://n8n.agvion.com
    volumes:
      - ~/.n8n:/home/node/.n8n
    expose:
      - "5678"  # expose only internally

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - n8n
